# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        avatar50:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: inset }
        avatar30:
            quality: 75
            filters:
                thumbnail: { size: [30, 30], mode: inset }
        avatar200:
            quality: 90
            filters:
                thumbnail: { size: [200, 200], mode: inset }
        cover160x200:
            quality: 100
            filters:
                thumbnail: { size: [160, 200], mode: inset }
        cover50x70:
            quality: 75
            filters:
                thumbnail: { size: [50, 70], mode: inset }