security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha512

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api_user_change_password:
            pattern:    ^/api/v1/user/change-password
            fos_oauth:  true
            stateless:  false

        api_public_forgot_password:
            methods: [POST]
            pattern:    ^/api/v1/user/forgot-password
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_public_user:
            methods: [GET, POST]
            pattern:    ^/api/v1/user
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_public_forgot_username:
            methods: [POST]
            pattern:    ^/api/v1/user/forgot-username
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_me:
            pattern:    ^/api/v1/user/me
            fos_oauth:  true
            stateless:  false

        api_public_documentary:
            methods: [GET]
            pattern: ^/api/v1/documentary
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_documentary:
            methods: [POST, PATCH]
            pattern:    ^/api/v1/documentary
            fos_oauth:  true
            stateless:  false

        api_public_video_source:
            methods: [GET]
            pattern: ^/api/v1/video-source
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_admin_video_source:
            methods: [POST, PUT, PATCH, DELETE]
            pattern: ^/api/v1/video-source
            fos_oauth:  true
            stateless:  false

        api_admin_comment:
            methods: [POST, PUT, PATCH, DELETE]
            pattern: ^/api/v1/comment
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_public_comment:
            methods: [GET]
            pattern: ^/api/v1/comment
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_public_activity:
            methods: [GET]
            pattern: ^/api/v1/activity
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_public_community:
            methods: [GET]
            pattern: ^/api/v1/community
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_sync:
            methods: [GET]
            pattern: ^/api/v1/sync
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_year:
            methods: [GET]
            pattern: ^/api/v1/year
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_watchlist:
            methods: [GET]
            pattern: ^/api/v1/watchlist
            fos_oauth:  true
            stateless:  false
            anonymous: true
#
        api_subscription:
            pattern: ^/api/v1/subscription
            fos_oauth:  true
            stateless:  false

        api_omdb:
            methods: [GET]
            pattern: ^/api/v1/omdb
            fos_oauth:  true
            stateless:  false
            anonymous: true

        api_youtube:
            methods: [GET]
            pattern: ^/api/v1/youtube
            fos_oauth:  true
            stateless:  false
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true

              # activate different ways to authenticate
              # https://symfony.com/doc/current/security.html#firewalls-authentication

              # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

            # Easy way to control access for large sections of your site
            # Note: Only the *first* access control that matches will be used

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
    - { path: ^/api/v1/user/me, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/v1/documentary, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
    - { path: ^/api/v1/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/video-source, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
    - { path: ^/api,       roles: IS_AUTHENTICATED_ANONYMOUSLY }