swiftmailer:
    transport:        smtp
    username:         jonathandevine@fastmail.com
    password:         c4s4akxqt58t4vaz
    host:             smtp.fastmail.com
    port:             465
    encryption:       ssl
    auth-mode:        login
    #spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false