#index:
#    path: /
#    controller: App\Controller\DefaultController::index


api_me:
  path: '/api/me'
  methods: ['GET']
  defaults:
    _controller: '\App\Controller\UserController::me'
    _api_resource_class: 'App\Entity\User'
    _api_collection_operation_name: 'collName_api_me'