#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

api_users:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\UserController

api_documentaries:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\DocumentaryController

api_video_sources:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\VideoSourceController

api_categories:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\CategoryController

api_comments:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\CommentController

api_activity:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\ActivityController

api_sync:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\SyncController

api_year:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\YearController

api_community:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\CommunityController

api_watchlist:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\WatchlistController