#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

api_me:
  path: '/api/me'
  methods: ['GET']
  defaults:
    _controller: '\App\Controller\UserController::me'
    _api_resource_class: 'App\Entity\User'
    _api_collection_operation_name: 'collName_api_me'

api_user_activate:
  path:     '/api/users/{id}/activate'
  methods:  ['GET']
  defaults:
    _controller: '\App\Controller\UserController::activate'
    _api_resource_class: 'App\Entity\User'
    _api_item_operation_name: 'activate'

api_user_reset_password_request:
  path:     '/api/users/{id}/reset-password-request'
  methods:  ['GET']
  defaults:
    _controller: '\App\Controller\UserController::resetPasswordRequest'
    _api_resource_class: 'App\Entity\User'
    _api_item_operation_name: 'reset-password-request'

api_user_reset_password:
  path:     '/api/users/{id}/reset-password'
  methods:  ['POST']
  defaults:
    _controller: '\App\Controller\UserController::resetPassword'
    _api_resource_class: 'App\Entity\User'
    _api_item_operation_name: 'reset-passwordt'