#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

api_users:
  type:     rest
  prefix:   api/v1
  resource: App\Controller\UserController