# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    postersUrl: 'http://localhost:8000/uploads/posters/'
    wideImagesUrl: 'http://localhost:8000/uploads/wide/'
    avatarsUrl: 'http://localhost:8000/uploads/avatar/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\UpdateCommentCountListener:
        class: App\EventListener\UpdateCommentCountListener
        tags:
            - { name: kernel.event_listener, event: comment.comment_created, method: onCommentCreated }
            - { name: kernel.event_listener, event: comment.comment_deleted, method: onCommentDeleted }

    App\EventListener\EmailSubscriptionListener:
        class: App\EventListener\EmailSubscriptionListener
        tags:
        - { name: kernel.event_listener, event: user.user_confirmed, method: onUserConfirmed }

    App\EventListener\UpdateFollowerAndFollowingCountListener:
        class: App\EventListener\UpdateFollowerAndFollowingCountListener
        tags:
        - { name: kernel.event_listener, event: follow.follow_saved, method: onFollowSaved }
        - { name: kernel.event_listener, event: follow.follow_deleted, method: onFollowDeleted }

    App\EventListener\UpdateWatchlistCountListener:
        class: App\EventListener\UpdateWatchlistCountListener
        tags:
        - { name: kernel.event_listener, event: watchlist.watchlist_created, method: onWatchlistCreated }

    App\EventListener\CommentActivityListener:
        class: App\EventListener\CommentActivityListener
        tags:
        - { name: kernel.event_listener, event: comment.comment_saved, method: onCommentSaved }

    App\EventListener\JoinedActivityListener:
        class: App\EventListener\JoinedActivityListener
        tags:
        - { name: kernel.event_listener, event: user.user_confirmed, method: onUserConfirmed }

    App\EventListener\WatchlistActivityListener:
        class: App\EventListener\WatchlistActivityListener
        tags:
        - { name: kernel.event_listener, event: watchlist.watchlist_created, method: onWatchlistCreated }

    App\EventListener\SendActivationEmailLIstener:
        class: App\EventListener\SendActivationEmailLIstener
        tags:
        - { name: kernel.event_listener, event: user.user_joined, method: onUserJoined }

    App\EventListener\SendConfirmationEmailFromAdminListener:
        class: App\EventListener\SendConfirmationEmailFromAdminListener
        tags:
        - { name: kernel.event_listener, event: user.user_created_by_admin, method: onUserCreatedByAdmin }

    App\EventListener\UpdateDocumentaryCount:
        class: App\EventListener\UpdateDocumentaryCount
        tags:
        - { name: kernel.event_listener, event: documentary.documentary_saved, method: onDocumentarySaved }


    app.http_kernel.cors_subscriber:
        class: App\EventListener\CorsSubscriber
        tags:
        - { name: kernel.event_subscriber }

    object_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        # Important! Tag this service or it wouldn't work
        tags:
        - { name: serializer.normalizer }